import ffmpeg from 'fluent-ffmpeg';

const getVideoThumbnail = (videoUrl: string): Promise<string[]> => {
  return new Promise((resolve, reject) => {
    const filenames: string[] = []; // Array to hold the filenames

    ffmpeg()
      .input(videoUrl)
      .complexFilter([
        {filter: 'scale', options: '640:-1'}, // Scale width to 640, adjust height proportionally
        {filter: 'crop', options: '640:480'}, // Crop the scaled video to 640x480
      ])
      .screenshots({
        count: 5, // Number of thumbnails to generate
        filename: './uploads/%b-thumb-%i.png', // Filename pattern with index
      })
      .on('end', () => {
        resolve(filenames); // Resolve with the array of filenames
      })
      .on('error', (error) => {
        console.error('ffmpeg', error);
        reject(error); // Reject the promise if an error occurs
      })
      .on('filenames', (generatedFilenames) => {
        // Capture the filenames generated by ffmpeg
        filenames.push(...generatedFilenames);
      });
  });
};

export default getVideoThumbnail;
